#!/usr/bin/python

import logging

import random
import signal
import string
import sys
import threading
import time

import logging_tree

import color_bucket_logger
# from color_bucket_logger import other_module

log = logging.getLogger('cbl_test')
log.setLevel(logging.DEBUG)


LOG_LEVELS = [(logging.DEBUG, 'DEBUG'),
              (logging.INFO, 'INFO'),
              (logging.WARNING, 'WARNING'),
              (logging.ERROR, 'ERROR'),
              (logging.CRITICAL, 'CRITICAL')]


class DefaultAttrFilter(object):
    def __init__(self, name=None, attrs=None):
        self.name = name
        self.attrs = attrs

    def filter(self, record):
        color_bucket_logger.add_default_record_attrs(record, self.attrs)
        return True


def _formatter(color_groups=None, fmt=None, default_color_by_attr=None, auto_color=False):
    if color_groups is None:
        color_groups = [('name', ['name', 'levelname'])]
    fmt = fmt or '%(levelname)s %(name)s %(message)s'
    # default_color_by_attr = default_color_by_attr or 'name'
    formatter = color_bucket_logger.ColorFormatter(fmt=fmt,
                                                   default_color_by_attr=default_color_by_attr,
                                                   color_groups=color_groups,
                                                   auto_color=auto_color)

    return formatter


def setup_logger(formatter):
    handler = logging.StreamHandler()
    handler.setLevel(logging.DEBUG)
    handler.setFormatter(formatter)

    handler.addFilter(DefaultAttrFilter(name="", attrs=['record']))
    log.addHandler(handler)

    return log, handler


def gen_loggers(base_logger_name):
    xs = string.ascii_uppercase
    ys = string.ascii_lowercase
    zs = string.digits
    x_size = 1
    y_size = 1
    z_size = 1

    for x in [''] + list(xs[0:x_size]):
        for y in [''] + list(ys[0:y_size]):
            for z in [''] + list(zs[0:z_size]):
                r = [base_logger_name] + [a for a in [x, y, z] if a]
                # print('r: %s' % r)
                name = '.'.join(r)
                # print('name: %s' % name)
                yield name


def func1(logger, level, **kwargs):
    extra = {'random': random.randint(0, 7),
             'other': 'i like cheese'}
    extra.update(kwargs)
    logger.log(level, 'foo blip level=%s' % level, extra=extra)


def func2(logger, level, **kwargs):
    msg = 'func2 test level=%s %%s' % level
    logger.log(level, msg, 'bar')


def throw_exc(msg=None):
    _msg = 'I object!'
    if msg:
        _msg += msg
    raise Exception(_msg)


# to test nested exceptions, esp on py3
def throw_deep_exc(msg=None):
    try:
        37 / 0
    except ZeroDivisionError as outer_e:
        log.exception(outer_e)
        try:
            doesnt_exist.append(1)  # noqa
        except Exception as inner_e:
            log.exception(inner_e)
            throw_exc(msg=msg)


def func3():
    pass
    # return throw_exc()


def func4():
    try:
        throw_deep_exc(msg=' to high prices!')
    except Exception as e:
        try:
            raise e
        except Exception as inner_e:
            log.exception(inner_e)


def random_sleep():
    time.sleep(0.5 * random.random())
    return


def gen_log_events(msg, sleep):
    loggers = []
    for name in gen_loggers('cbl_test'):
        _logger = logging.getLogger(name)
        loggers.append(_logger)

    logging_tree.printout()
    for logger in loggers:
        for level, levelname in LOG_LEVELS[:3]:
            func1(logger, level)
            random_sleep()
        for level, levelname in LOG_LEVELS[:3]:
            func2(logger, level, blip='1212312')
            logger.log(level, msg)
            random_sleep()
        # for level, levelname in LOG_LEVELS:
        try:
            func3()
            random_sleep()
        except Exception as e:
            log.exception(e)
        random_sleep()

        # func4()
        # random_sleep()

    color_bucket_logger.other_module.func3()


def _gen_log_events(handler):
    gen_log_events()
    fmt = '%(asctime)s %(threadName)-2s level: %(levelname)s module: %(module)s name: %(name)s funcName: %(funcName)s %(message)s'

    color_groups2 = [('funcName', ['message', 'module', 'name']),
                     ('levelname', ['levelname'])]
    formatter = _formatter(color_groups2, fmt,
                           default_color_by_attr='funcName')
    handler.setFormatter(formatter)
    gen_log_events()


def main(args):
    color_groups = [
                    # ('thread', ['threadName']),
                    # ('threadName', ['thread']),
                    # ('levelname', ['levelno']),
                    ('process', ['processName']),
                    ('threadName', ['thread', 'exc_text']),
                    # ('threadName', ['thread', 'message',]),
                    ('name', ['module', 'filename']),
                    ('funcName', ['lineno']),
                    ('levelname', ['levelno'])
    ]
    # fmt = '%(asctime)s %(relativeCreated)d %(levelname)s %(module)s %(name)s %(funcName)s %(random)s %(message)s'
    # fmt = '%(asctime)s %(threadName)-2s level: %(levelname)s module: %(module)s name: %(name)s funcName: %(funcName)s %(message)s'
    fmt_all = '%(asctime)s %(levelname)-0.1s %(process)d %(threadName)s %(name)s %(funcName)s %(lineno)d - %(message)s'

    formatter = _formatter(color_groups, fmt_all,
                           default_color_by_attr='name',
                           auto_color=True,
                           # default_color_by_attr='name')
                           )
    logger, handler = setup_logger(formatter)

    import logging_tree
    logging_tree.printout()

    threads = []

    main_thread = threading.currentThread()

    thread_count = 1
    for i in range(thread_count):
        t = threading.Thread(target=gen_log_events, name='Thrd-%s' % i,
                             args=('msg from thread #%s' % i, i))
        threads.append(t)
        t.daemon = True
        t.start()

    for t in threading.enumerate():
        if t is main_thread:
            continue
        # logging.debug('joining %s', t.getName())
        t.join()
    return 0

def sigint_handler(signal, frame):
    sys.exit(0)

if __name__ == '__main__':
    # signal.signal(signal.SIGINT, sigint_handler)

    sys.exit(main(sys.argv[:]))
