#!/usr/bin/env python

import os
import sys

from gen_log_entries import run_threaded, log_setup, show_setup

CONFIG = 'deep-exceptions.yml'


if __name__ == '__main__':
    log_config_file = os.path.join(os.path.dirname(__file__), CONFIG)

    log_setup(log_config_file)
    show_setup()
    run_threaded(thread_count=3, throw_exc=True)
    sys.exit()
