---
disable_existing_loggers: false
filters: {}
formatters:
  color_verbose:
    (): color_bucket_logger.ColorFormatter
    fmt: "%(asctime)s %(levelname)s %(processName)s pid=%(process)d %(threadName)s %(name)s %(funcName)s %(filename)s %(lineno)s - %(message)s"
    auto_color: true
handlers:
  console:
    class: logging.StreamHandler
    formatter: color_verbose
    level: DEBUG
    stream: ext://sys.stderr
loggers: {}
root:
  level: DEBUG
  handlers:
    - console
version: 1
