#!/usr/bin/env python

import logging
import logging.config
import os
import sys

import yaml

from gen_log_entries import run_threaded

log_config_path = os.path.join(os.path.dirname(__file__), 'threaded_config.yml')

with open(log_config_path, 'r') as log_config_fd:
    log_config = yaml.safe_load(log_config_fd)

conf = logging.config.dictConfig(log_config)

if __name__ == '__main__':
    run_threaded()
    sys.exit()
