---
disable_existing_loggers: false
filters: {}
formatters:
  color_verbose:
    (): color_bucket_logger.ColorFormatter
    # Only one processName here (MainProcess) so not included here
    format: '[%(asctime)s %(process)05d %(threadName)s:%(thread)d %(levelname)-0.1s] %(name)s %(funcName)s:%(lineno)-3d - %(message)s'

    # Make the default color of the message correspond to the logger name
    default_color_by_attr: 'thread'

    # Automatically choose color buckets for other fields based on their values.
    # Each log record field will colorize itself, except for the color buckets grouped
    # together via color_groups.
    auto_color: true

    # If there are fields that should share the same color bucket, 'color_groups'
    # defines which field's color is used. Each entry is a list or tuple, the first
    # item is the field name used to choose the color, the second field is a list of
    # fieldnames that will use that color.
    #
    # For example, to let 'process' and 'processName' fields use the 'process' color,
    # a color groups entry: "['process', ['processName']]'
    color_groups:
        # - ['process', ['processName']]
      - ['levelname', ['levelname']]
      - ['funcName', ['lineno']]
      - ['thread', ['threadName', 'process', 'processName']]
handlers:
  console:
    class: logging.StreamHandler
    formatter: color_verbose
    level: DEBUG
    stream: ext://sys.stderr
loggers: {}
root:
  level: DEBUG
  handlers:
    - console
version: 1
