#!/usr/bin/env python

import os
import sys

from gen_log_entries import run, log_setup, show_setup

CONFIG = 'yaml-config.yml'


if __name__ == '__main__':
    log_config_file = os.path.join(os.path.dirname(__file__), CONFIG)

    log_setup(log_config_file)
    show_setup()
    run()
    sys.exit()
